config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", registrations: 'users/registrations'  }
  # home
  root 'home#index'
  get 'home/reset_password' => 'home#reset_password', as: 'reset_password'
  patch 'home/update_reset_password' => 'home#update_reset_password', as: 'send_reset_password'

  #dashboard
  get 'dashboard' => 'dashboard#index', as: 'dashboard'
  #create_board
  get 'showboard/:id/:from' => 'create_boards#show', as: 'show_board'
  patch	'create_boards/:id' => 'create_boards#update', as: 'update_board'
  delete 'create_boards/:id' => 'create_boards#destroy', as: 'delete_board'
  patch 'update_group/:id/:group' => 'create_boards#update_group', as: 'update_group'
  resources :create_boards

  #cards
  get 'cards/:cb_id' => 'cards#index', as: 'view_cards'
  get 'newcard/:cb_id' => 'cards#new', as: 'new_card'
  post 'cards/:cb_id' => 'cards#create', as: 'create_card'
  get 'card/:cb_id/:card_id/edit' => 'cards#edit', as: 'edit_card'
  patch 'card/:cb_id/:card_id' => 'cards#update', as: 'update_card'
  delete 'card/:cb_id/:card_id' => 'cards#destroy', as: 'delete_card'
  resources :cards

  # addcards
  get 'addcards/view/:cb_id/:card_id/:id' => 'addcards#index', as: 'view_addcards'
  get 'newcard/:cb_id/:card_id' => 'addcards#new', as: 'newcard'
  post 'addcards/:cb_id/:card_id' => 'addcards#create', as: 'create_addcard'
  get 'addcards/edit/:cb_id/:card_id/:id' => 'addcards#edit', as: 'edit_addcard'
  get 'addcards/edit_desc/:cb_id/:card_id/:id' => 'addcards#edit_desc', as: 'edit_desc'
  get 'addcomment/edit/:cb_id/:card_id/:id' => 'addcards#edit_comment', as: 'edit_comment'
  patch 'addcards/:cb_id/:card_id/:id' => 'addcards#update', as: 'update_addcard'
  patch 'attendance/:cb_id/:card_id/:id' => 'addcards#attendance', as: 'attendance'
  patch 'update_conclusion/:cb_id/:card_id/:id' => 'addcards#update_conclusion', as: 'update_conclusion'
  post 'generate_mom/:cb_id/:card_id/:id' => 'addcards#generate_mom', as: 'generate_mom'
  post 'create_hostandscribe/:cb_id/:card_id/:id' => 'addcards#create_hostandscribe', as: 'create_hostandscribe'
  delete 'addcards/:cb_id/:card_id/:id' => 'addcards#destroy', as: 'delete_addcard'
  resources :addcards
  # todo section
  post 'todo/:cb_id/:card_id/:id' => 'addcards#create_todo', as: 'create_todo'
  delete 'todo/:cb_id/:card_id/:id' => 'addcards#delete_todo', as: 'delete_todo'
  patch 'updatetodo/:cb_id/:card_id/:id' => 'addcards#update_todo', as: 'update_todo'
  patch 'updatecheckbox/:cb_id/:card_id/:id' => 'addcards#update_checkbox', as: 'update_checkbox'
  # identify section
  post 'identify/:cb_id/:card_id/:id' => 'addcards#create_identify', as: 'create_identify'
  delete 'identify/:cb_id/:card_id/:id' => 'addcards#delete_identify', as: 'delete_identify'
  patch 'updateidentify/:cb_id/:card_id/:id' => 'addcards#update_identify', as: 'update_identify'
  patch 'updateidentify_checkbox/:cb_id/:card_id/:id' => 'addcards#update_identify_checkbox', as: 'update_identify_checkbox'

  # addcomments``
  post 'addcomments/:cb_id/:card_id/:id' => 'addcomments#create', as: 'create_addcomment'
  patch 'addcomments/:cb_id/:card_id/:id' => 'addcomments#update', as: 'update_addcomment'
  delete 'addcomments/:cb_id/:card_id/:id' => 'addcomments#destroy', as: 'delete_addcomment'

  # Edit User Account
  patch 'editaccounts' => 'editaccounts#update', as: 'update_account'

  # Profile pic
  post 'create/profilepic' => 'profilepics#create', as: 'create_pic'
  patch 'update/profilepic' => 'profilepics#update', as: 'update_pic'
  delete 'delete/profilepic' => 'profilepics#destroy', as: 'delete_pic'

  # All Users
  get 'allusers' => 'allusers#index', as: 'view_allusers'
  patch 'update/role/:id' => 'allusers#update', as: 'update_role'
  patch 'update/admin/:id/:admin' => 'allusers#updateadmin', as: 'update_admin'

  # Project Management Monitoring System Section
  # Projects
  get 'projects/dashboard' => 'projects#dashboard', as: 'projects_dashboard'
  get 'yourprojects/:pw_id/:rocks_owner' => 'projects#index', as: 'view_projects'
  get 'allprojects/:pw_id/:rocks_owner' => 'projects#allprojects', as: 'view_allprojects'
  get 'archivedprojects/:pw_id/:rocks_owner' => 'projects#archived', as: 'view_archived'
  patch 'sendarchivedprojects/:pw_id/:rocks_owner' => 'projects#send_archived', as: 'send_archived'
  patch 'returnarchivedprojects/:pw_id/:rocks_owner' => 'projects#return_archived', as: 'return_archived'
  post 'sync_rock/:pw_id/:rocks_owner' => 'projects#sync_rock', as: 'sync_rock'


  # Workspace
  post 'create/workspace' => 'project_workspaces#create_workspace', as: 'create_workspace'
  patch 'update/workspace' => 'project_workspaces#update_workspace', as: 'update_workspace'
  delete 'delete/workspace/:id' => 'project_workspaces#delete_workspace', as: 'delete_workspace'

 # Rocks
  post 'create/rocks/:pw_id/:rocks_owner' => 'projects#create_rocks', as: 'create_rocks'
  patch 'update/rocks/:pw_id/:rocks_owner' => 'projects#update_rocks', as: 'update_rocks'
  # patch 'update/rocks_automate' => 'projects#automate_rocks', as: 'automate_rocks'
  patch 'update/rocks_reviewed_by/:pw_id/:rocks_owner' => 'projects#update_rocks_reviewedby', as: 'update_rocks_reviewedby'
  delete 'delete/rocks/:pw_id/:id/:rocks_owner' => 'projects#delete_rocks', as: 'delete_rocks'

  #Rock messages
  post 'projects/rockmessages/:pw_id/:rock_id/:rocks_owner' => 'projects#create_rockmessage', as: 'create_rockmessage'
  patch 'projects/rockmessages/:pw_id/:rock_id/:id/:rocks_owner' => 'projects#update_rockmessage', as: 'update_rockmessage'
  delete 'delete/rockmessages/:pw_id/:rock_id/:id/:rocks_owner' => 'projects#delete_rockmessage', as: 'delete_rockmessage'

  # Milestones
  post 'create/milestones/:pw_id/:rock_id/:rocks_owner' => 'projects#create_milestones', as: 'create_milestones'
  patch 'update/milestones/:pw_id/:rocks_owner' => 'projects#update_milestones', as: 'update_milestones'
  delete 'delete/milestones/:pw_id/:rock_id/:id/:rocks_owner' => 'projects#delete_milestones', as: 'delete_milestones'

  #Milestone messages
  post 'projects/messages/:pw_id/:milestone_id/:rocks_owner' => 'projects#create_message', as: 'create_message'
  patch 'projects/messages/:pw_id/:milestone_id/:id/:rocks_owner' => 'projects#update_message', as: 'update_message'
  delete 'delete/messages/:pw_id/:rock_id/:milestone_id/:id/:rocks_owner' => 'projects#delete_message', as: 'delete_message'

  # Sub Milestones
  post 'create/submilestones/:pw_id/:rock_id/:milestone_id/:rocks_owner' => 'submilestones#create_submilestones', as: 'create_submilestones'
  patch 'update/submilestones/:pw_id/:rocks_owner' => 'submilestones#update_submilestones', as: 'update_submilestones'
  delete 'delete/submilestones/:pw_id/:rock_id/:milestone_id/:id/:rocks_owner' => 'submilestones#delete_submilestones', as: 'delete_submilestones'

  # Sub Milestone messages
  post 'submilestones/submessages/:pw_id/:milestone_id/:submilestone_id/:rocks_owner' => 'submilestones#create_submessage', as: 'create_submessage'
  patch 'submilestones/submessages/:pw_id/:rock_id/:milestone_id/:submilestone_id/:id/:rocks_owner' => 'submilestones#update_submessage', as: 'update_submessage'
  delete 'delete/submessages/:pw_id/:rock_id/:milestone_id/:submilestone_id/:id/:rocks_owner' => 'submilestones#delete_submessage', as: 'delete_submessage'

  # Sub2milestones
  post 'create/sub2milestones/:pw_id/:rock_id/:milestone_id/:submilestone_id/:rocks_owner' => 'sub2milestones#create_sub2milestones', as: 'create_sub2milestones'
  patch 'update/sub2milestones/:pw_id/:rocks_owner' => 'sub2milestones#update_sub2milestones', as: 'update_sub2milestones'
  delete 'delete/sub2milestones/:pw_id/:rock_id/:milestone_id/:submilestone_id/:id/:rocks_owner' => 'sub2milestones#delete_sub2milestones', as: 'delete_sub2milestones'

  # Sub2milestone messages
  post 'sub2milestones/sub2messages/:pw_id/:milestone_id/:submilestone_id/:rocks_owner' => 'sub2milestones#create_sub2message', as: 'create_sub2message'
  patch 'sub2milestones/sub2messages/:pw_id/:rock_id/:milestone_id/:submilestone_id/:id/:rocks_owner' => 'sub2milestones#update_sub2message', as: 'update_sub2message'
  delete 'delete/sub2messages/:pw_id/:rock_id/:milestone_id/:submilestone_id/:id/:rocks_owner' => 'sub2milestones#delete_sub2message', as: 'delete_sub2message'

  # Gantt Section
  get 'gantt/index' => 'gantt#index', as: 'gantt'
  post 'gantt/update_gantt' => 'gantt#update_gantt', as: 'update_gantt'

  scope '/api' do
    get "/data", :to => "gantt#data"
    
    post "/task", :to => "task#add"
    put "/task/:id", :to => "task#update"
    delete "/task/:id", :to => "task#delete"

    post "/link", :to => "link#add"
    put "/link/:id", :to => "link#update"
    delete "/link/:id", :to => "link#delete"
  end


end

app/views/shared/_navbar.html.erb
<div class="navbar d-flex justify-content-between">
  <!-- Left Section -->
  <div class="mx-2 d-flex ">
    <!-- Logo -->
    <%= link_to dashboard_path(), class:"nav-element #{'nav-active' if request.original_url.include? "dashboard"}" do %>
      <div class="m-auto d-flex">
        <div class="cem-logo"><%= image_tag ("cem-logo.png") %></div>
        <div class="m-auto">ITS L10 MEETING</div>
      </div>
    <% end %>
    <!-- Create Button -->
    <div class="create-relative">
      <div class="nav-element create-btn">Create</div>
        <!-- create board modal -->
      <div class="new-board">
        <%= form_with scope: :create_board, url:create_boards_path, method: :post, local: true do |form| %>
          <div class="pb-1">
            <%= form.label 'Board title*', style: "display: block" %>
            <%= form.text_field :board_title, required: true, class:"px-2" %>
          </div>
          <div class="pb-1">
            <%= form.label 'Board descrition(optional)', style: "display: block" %>
            <%= form.text_field :board_desc, class:"px-2" %>
          </div>
          <%= form.submit "Save", class:"btn btn-success w-100 mt-1"%>
        <% end %>
      </div>
    </div>

    <!-- All Users Section -->
    <% if current_user.email == "jpbocatija@cem-inc.org.ph" %>
      <%= link_to "All Users",view_allusers_path, class:"nav-element #{'nav-active' if request.original_url.include? "allusers"}" %>
    <% elsif current_user.admin == true %>
      <%= link_to "All Users",view_allusers_path, class:"nav-element #{'nav-active' if request.original_url.include? "allusers"}" %>
    <% end %>
     <!-- Projects Section -->
     <%= link_to projects_dashboard_path, class:"nav-element",target: :_blank  do %>
      <div class="m-auto d-flex align-items-center">
        <div class="new-tab-logo"><%= image_tag ("new_tab.png") %></div>
        <div class="m-auto">RMMS</div>
      </div>
    <% end %>
  </div>
  <!-- Create button background -->
  <div class="create-bg account-bg"></div>
  <!-- Right Section -->
  <div class="d-flex align-items-center mx-4">
    <div>
      <input type="text" placeholder="&#xF002; Search" style="font-family: Roboto, 'Font Awesome 5 Free';" class="search-bar" />
    </div>
    <div class="account-section">
      <div class="circle">
        <span class="circle-inner"><%= @name_initial %></span>
      </div>
      <div class="account-con">
        <h5 class="mx-4 mt-4">Account</h5>
        <div class="d-flex justify-content-center px-3">
          <div class="profile-pic">
            <%= form_with url:create_pic_path, method: :post, local: true do |f| %>
                <%= f.hidden_field :avatar, value: "" %>
                <% if !@profilepic.blank? %>
                  <%= image_tag @profilepic.pic, style:"width:50px; height:50px;" %>
                <% else %>
                  <%= image_tag ("profile-pic.png"), style:"width:50px; height:50px;" %>
                <% end %>
                <div class="align-items-center align-items-center pic-button"> 
                  <label for="pic" style="margin-right:10px;">
                    <%= image_tag ("upload.png"),style:"cursor:pointer" %>
                    <%= f.file_field :pic, class:"d-none", id:"pic", required:true %>
                  </label>
                  <%= image_submit_tag("submit.png") %>
                </div>
            <% end %>
          </div>
          <div>
            <div><%= current_user.first_name + " " + current_user.last_name %></div>
            <div><i><%= current_user.email %></i></div>
          </div>
        </div>
        <hr style="margin-top: 20px; margin-bottom: 10px;"/>
        <div class="edit-account account-menu px-4 py-2">Edit Account</div>
        <hr style="margin:10px 0;"/>
        <%= link_to destroy_user_session_path,data: {turbo_method: :delete, turbo_confirm: 'Are you sure you want to logout?'}, class:"logout" do %>
          <div class="account-menu px-4 py-2" style="margin-bottom:10px;">Logout</div>
        <% end %>
      </div>
      <!-- Edit Account -->
      <div class="edit-account-con">
        <%= form_with url:update_account_path, method: :patch, local: true do |f| %>
          <div style="font-weight: bold; font-size: 1.5rem;text-align: center;">-Edit Account-</div>
          <div class="field mt-2">
            <b><%= f.label 'First Name' %></b>
            <div><%= f.text_field :first_name, autofocus: true, autocomplete: "first_name",class:"w-100 px-2", placeholder:"Enter first name",value:current_user.first_name,required:true %></div>
          </div>
    
          <div class="field">
            <b><%= f.label 'Last Name' %></b>
            <div><%= f.text_field :last_name, autofocus: true, autocomplete: "last_name",class:"w-100 px-2", placeholder:"Enter last name",value:current_user.last_name,required:true %></div>
          </div>
        
          <div class="field mt-4">
            <b><%= f.label :email %></b>
            <div><%= f.email_field :email, autofocus: true, autocomplete: "email",class:"w-100 px-2", placeholder:"Enter email",value:current_user.email,required:true %></div>
          </div>
        
          <div class="field">
            <b><%= f.label :password %></b>
            <div><%= f.password_field :password, autofocus: true, autocomplete: "password",class:"w-100 px-2",id:"my-password", placeholder:"Enter password",required:true,minlength:"6" %></div>
            <div class="d-flex align-items-center mt-1">
              <input type="checkbox" onclick="showPassword()">
              <span style="margin-left: 10px; font-size: 12px;">Show Password</span> 
            </div>
          </div>
        
          <div class="actions mt-3">
            <%= f.submit "Submit", class:"continue-btn" %>
          </div>
        <% end %>
        <div class="mt-2" id="back" style="cursor:pointer; color:blue; text-align: center;"><u><--back</u></div>
      </div>
    </div>
  </div>
  
</div>

<script>
  

  $(document).ready(function(){

    // create board toggle
    $(".new-board").css("display", "none")
    $(".create-bg").css("display", "none")
    $(".create-btn").click(function(){
      $(".new-board").addClass("w3-animate-zoom")
      $(".new-board").toggle();
      $(".create-bg").toggle();
    });

    // account toggle
    $(".account-con").css("display", "none")
    $(".circle").click(function(){
      $(".account-con").addClass("w3-animate-zoom")
      $(".account-con").toggle();
      $(".account-bg").toggle();
      $(".edit-account-con").hide();
    });
    // hide create and account bg
    $(".account-bg").click(function(){
      $(".new-board").hide();
      $(".account-con").hide();
      $(".edit-account-con").hide()
      $(this).hide();
    });


    // Edit account
    $(".edit-account-con").css("display", "none")
    $(".edit-account").click(function(){
      $(".account-con").hide();
      $(".edit-account-con").show();
    });
    // go back link
    $("#back").click(function(){
      $(".account-con").show();
      $(".edit-account-con").hide();
    });

    // show profile pic
    $(".pic-button").css("display", "none")
    $( ".profile-pic" ).hover(
      function() {
      $( this ).find(".pic-button").css("display", "flex")
      },
      function() {
      $( this ).find(".pic-button").hide()
      } 
    );

  });

  // show password
  function showPassword() {
    var x = document.getElementById("my-password");
    console.log("hellooooo")
    if (x.type === "password") {
      x.type = "text";
    } else {
      x.type = "password";
    }
  }

  


</script>